language: node_js
node_js:
  - 4.2.4
before_install:
  - cp ./server/config.example.js ./server/config.js
  - cp ./native/sharedNative/config/config.example.js ./native/sharedNative/config/config.js
install:
  - npm install -g rnpm
  - npm run install:all
notifications:
  email: false
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
